display_timer(timer) ::= <<
<tr>
    <th>Mean Time (ms)</th>
    <td>$timer.mean$</td>
</tr>
<tr>
    <th>50th Percentile</th>
    <td>$timer.p50$</td>
</tr>
<tr>
    <th>75th Percentile</th>
    <td>$timer.p50$</td>
</tr>
<tr>
    <th>95th Percentile</th>
    <td>$timer.p95$</td>
</tr>
<tr>
    <th>98th Percentile</th>
    <td>$timer.p98$</td>
</tr>
<tr>
    <th>99th Percentile</th>
    <td>$timer.p99$</td>
</tr>
<tr>
    <th>999th Percentile</th>
    <td>$timer.p999$</td>
</tr>
<tr>
    <th>Standard Deviation</th>
    <td>$timer.std$</td>
</tr>
>>