footer() ::= <<
<footer class="row">
    <div class="large-12 columns">
        <p class="right"><small>
            API:&nbsp;
            <a href="/ping">Ping</a>&nbsp;&middot;&nbsp;
            <a href="/health">Health Check</a>&nbsp;&middot;&nbsp;
            <a href="/metrics">Metrics</a>&nbsp;&middot;&nbsp;
            <a href="/metrics/notification/topic">Notification Metrics</a>&nbsp;&middot;&nbsp;
            <a href="/metrics/callback/host">Subscription Metrics</a></small>
        </p>
    </div>
</footer>
>>