head() ::= <<
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>$constants.defaultTitle$</title>
    <link rel="stylesheet" href="$constants.cssBase$/foundation.css"/>
    <link rel="stylesheet" href="$constants.cssBase$/foundation-icons/foundation-icons.css"/>
    <script src="$constants.jsBase$/vendor/modernizr.js"></script>
    <script src="$constants.jsBase$/vendor/jquery.js"></script>
    <script src="$constants.jsBase$/custom.js"></script>
</head>
>>